apiVersion: argoproj.io/v0beta9000
kind: Workflow
metadata:
  generateName: global-config-
  namespace: argo-namespace
spec:
  entrypoint: whalesay
  serviceAccountName: argo-account
  templates:
  - name: whalesay
    activeDeadlineSeconds: 100
    container:
      command:
      - cowsay
      image: docker/whalesay:latest
  - name: say
    script:
      command:
      - python3
      image: image-say
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        print('hello')
